spring:
  config:
    import:
      - classpath:db.properties
  profiles:
    include:
      - db
    group:
      default: local
      local: h2
      db: local
      dev: local
      prod:
  redis:
    host: test
    port: 6379
    password: password
