spring:
  config:
    import:
      - classpath:db.properties
  profiles:
    include:
      - db
    group:
      default: local
      local: h2
      db: local
      dev: local
      prod:
  redis:
    host: 127.0.0.1
    port: 6379
    password:

logging:
  level:
    org:
      springframework:
        cache: DEBUG
