CREATE TABLE IF NOT EXISTS MEMBER
(
    id        bigint generated by default as identity,
    public_id varchar(255) UNIQUE NOT NULL,
    nickname  varchar(255)        NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS IDX_MEMBER_PUBLIC_ID ON MEMBER (public_id);

CREATE TABLE IF NOT EXISTS QUIZ
(
    id                bigint generated by default as identity,
    public_id         varchar(255) UNIQUE NOT NULL,
    title             varchar(255) UNIQUE NOT NULL,
    content           varchar(255)        NOT NULL,
    release_at        timestamp           NOT NULL,
    answer_release_at timestamp           NOT NULL,
    created_at        timestamp           NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_at        timestamp           NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS IDX_QUIZ_PUBLIC_ID on QUIZ (public_id);

CREATE TABLE IF NOT EXISTS QUIZ_CHOICE
(
    id         bigint generated by default as identity,
    public_id  varchar(255) UNIQUE NOT NULL,
    quiz_id    bigint              NOT NULL, -- QUIZ.id
    text       varchar(255)        NOT NULL,
    is_answer  boolean             NOT NULL DEFAULT TRUE,
    created_at timestamp           NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_at timestamp           NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS IDX_CHOICE_PUBLIC_ID on QUIZ_CHOICE (public_id);
CREATE INDEX IF NOT EXISTS IDX_CHOICE_QUIZ_ID on QUIZ_CHOICE (quiz_id);

CREATE TABLE IF NOT EXISTS QUIZ_SUBMIT
(
    id           bigint generated by default as identity,
    submitter_id bigint    NOT NULL, -- MEMBER.id
    quiz_id      bigint    NOT NULL, -- QUIZ.id
    choice_id    bigint    NOT NULL, -- QUIZ_CHOICE.id
    created_at   timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_at   timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS IDX_QUIZ_SUBMIT_QUIZ_ID_SUBMITTER_ID on QUIZ_SUBMIT (quiz_id, submitter_id);
CREATE INDEX IF NOT EXISTS IDX_QUIZ_SUBMIT_SUBMITTER_ID on QUIZ_SUBMIT (submitter_id);
CREATE INDEX IF NOT EXISTS IDX_QUIZ_SUBMIT_CHOICE_ID on QUIZ_SUBMIT (choice_id);
