CREATE TABLE IF NOT EXISTS QUIZ
(
    id                bigint generated by default as identity,
    public_id         varchar(255) UNIQUE NOT NULL,
    title             varchar(255)        NOT NULL,
    content           varchar(255)        NOT NULL,
    release_at        timestamp           NOT NULL,
    answer_release_at timestamp           NOT NULL,
    created_at        timestamp           NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_at        timestamp           NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (id)
);
CREATE INDEX IDX_QUIZ_PUBLIC_ID on QUIZ (public_id);

CREATE TABLE IF NOT EXISTS QUIZ_CHOICE
(
    id         bigint generated by default as identity,
    public_id  varchar(255) UNIQUE NOT NULL,
    quiz_id    bigint              NOT NULL,
    text       varchar(255)        NOT NULL,
    is_answer  boolean             NOT NULL DEFAULT TRUE,
    created_at timestamp           NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_at timestamp           NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (id)
);
CREATE INDEX IDX_CHOICE_PUBLIC_ID on QUIZ_CHOICE (public_id);
CREATE INDEX IDX_CHOICE_QUIZ_ID on QUIZ_CHOICE (quiz_id);

CREATE TABLE IF NOT EXISTS QUIZ_SUBMIT
(
    id         bigint generated by default as identity,
    member_id  bigint    NOT NULL,
    quiz_id    bigint    NOT NULL,
    choice_id  bigint    NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (id)
);
CREATE INDEX IDX_QUIZ_SUBMIT_MEMBER_ID on QUIZ_SUBMIT (member_id);
CREATE INDEX IDX_QUIZ_SUBMIT_QUIZ_ID on QUIZ_SUBMIT (quiz_id);
CREATE INDEX IDX_QUIZ_SUBMIT_CHOICE_ID on QUIZ_SUBMIT (choice_id);
