CREATE TABLE IF NOT EXISTS quiz
(
    id         bigint generated by default as identity,
    title      varchar(255) NOT NULL,
    content    varchar(255) NOT NULL,
    release_at timestamp    NOT NULL,
    created_at timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_at timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS quiz_choice
(
    id         bigint generated by default as identity,
    quiz_id    bigint       NOT NULL,
    text       varchar(255) NOT NULL,
    created_at timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_at timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (id)
);
