CREATE TABLE IF NOT EXISTS quiz
(
    id        bigint generated by default as identity,
    title     varchar(255) NOT NULL,
    content   varchar(255) NOT NULL,
    releaseAt timestamp    NOT NULL,
    createdAt timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updatedAt timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (id)
)
